---
name: 3 - BUG - report a malfunction
description: Report a malfunction like checker crashes
title: "[BUG] "
labels: ["bug", "TRIAGE"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out all required fields below. 
        
        Please ensure that this issue does NOT report any **false positive** detections. 
        To report 'false positive' detections use the apropiate template.
  
  - type: checkboxes
    attributes:
      label: I'm sure that
      options:
        - label: This issue does not report a **false-positive** detection (use dedicated template for this)
          required: true
        - label: This issue does not request a **change or removal of existing check** (use dedicated template for this)
          required: true
        - label: This issue does not request a **new feature** (use dedicated template for this)
          required: true
        - label: There is no other (open) issue with the same topic (use the search!)
          required: true

  - type: textarea
    id: problem_description
    attributes:
      label: Description of problem
      description: Please provide a detailed description of the problem
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true
  
  - type: dropdown
    id: reproducible
    attributes:
      label: Can be reproduced
      description: Is this issue consistently reproducible?
      options:
        - "Please select"
        - "Yes"
        - "No"
    validations:
      required: true
  
  - type: input
    id: repository_link
    attributes:
      label: Link to repository
      description: Please provide the link to the repository where the issue occurs
      placeholder: "https://github.com/username/ioBroker.adaptername"
    validations:
      required: true
  
  - type: input
    id: checker_version
    attributes:
      label: Checker version
      description: What version of the repochecker are you using?
      placeholder: "4.2.0"
    validations:
      required: true
