blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ioBroker/ioBroker.repochecker/blob/master/README.md
    about: Please check the documentation before creating an issue