---
name: 2 - NEW CHECK - suggest a new check
description: Suggest to add a new check or to extend an existing check
title: "[NEW CHECK] "
labels: ["enhancement", "TRIAGE"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new check. Please provide all required information below.
  
  - type: checkboxes
    attributes:
      label: I'm sure that
      options:
        - label: This issue does not report a **false-positive** detection (use dedicated template for this)
          required: true
        - label: This issue does not request a **change or removal of existing check** (use dedicated template for this)
          required: true
        - label: There is no other (open) issue with the same topic (use the search!)
          required: true

  - type: textarea
    id: check_description
    attributes:
      label: Description of check to be added
      description: Please provide a detailed description of the new check you would like to see added
      placeholder: Describe the new check, what it should validate, and why it would be useful...
    validations:
      required: true
  
  - type: input
    id: repository_link
    attributes:
      label: Link to repository
      description: Please provide a link to a repository that would benefit from this check
      placeholder: "https://github.com/username/ioBroker.adaptername"
    validations:
      required: true
  
  - type: input
    id: checker_version
    attributes:
      label: Checker version
      description: What version of the repochecker are you using?
      placeholder: "4.2.0"
    validations:
      required: true
