const STATE_ROLE_RULES = {
    'adapter.messagebox': {
        types: ['object'],
        write: true,
    },
    'adapter.wakeup': {
        types: ['boolean'],
        write: true,
    },
    button: {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'button.close.blind': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.close.tilt': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.fastforward': {},
    'button.fastreverse': {},
    'button.forward': {},
    'button.long': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'button.mode.': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.mode.auto': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.mode.manual': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.mode.silent': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.next': {},
    'button.open.blind': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.open.door': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.open.tilt': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.open.window': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.pause': {},
    'button.play': {},
    'button.press': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'button.prev': {},
    'button.resume': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.reverse': {},
    'button.start': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.stop': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.stop.tilt': {
        types: ['boolean'],
        read: false,
        write: true,
    },
    'button.volume.down': {},
    'button.volume.up': {},
    chart: {},
    date: {
        types: ['string', 'number'],
    },
    'date.end': {},
    'date.forecast.1': {},
    'date.start': {},
    'date.sunrise': {},
    'date.sunset': {},
    dayofweek: {},
    html: {
        types: ['string'],
    },
    indicator: {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.alarm': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.alarm.fire': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.alarm.flood': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.alarm.health': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.alarm.secure': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.connected': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.direction': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.error': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.lowbat': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.maintenance': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.maintenance.alarm': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.maintenance.lowbat': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.maintenance.unreach': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.maintenance.waste': {},
    'indicator.reachable': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'indicator.working': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'info.address': {},
    'info.display': {},
    'info.firmware': {},
    'info.hardware': {},
    'info.ip': {},
    'info.mac': {},
    'info.model': {},
    'info.name': {},
    'info.port': {},
    'info.serial': {},
    'info.standby': {},
    'info.status': {},
    json: {
        types: ['string'],
    },
    level: {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.bass': {},
    'level.battery': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.battery.max': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.battery.min': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.blind': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.brightness': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.blue': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.cie': {
        types: ['string'],
        read: true,
        write: true,
    },
    'level.color.green': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.hue': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.luminance': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.red': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.rgb': {
        types: ['string'],
        read: true,
        write: true,
    },
    'level.color.rgbw': {
        types: ['string'],
        read: true,
        write: true,
    },
    'level.color.saturation': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.temperature': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.color.white': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.current': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.current.max': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.current.min': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.curtain': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.default': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.dimmer': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.effect': {
        types: ['string'],
        read: true,
        write: true,
    },
    'level.fill': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.frequency': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.frequency.max': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.frequency.min': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.humidity': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.max': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.min': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.mode.airconditioner': {},
    'level.mode.cleanup': {},
    'level.mode.fan': {},
    'level.mode.swing': {},
    'level.mode.thermostat': {},
    'level.mode.work': {},
    'level.pressure': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.pressure.max': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.pressure.min': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.setting.color.temperature': {},
    'level.speed': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.temperature': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.tilt': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.timer': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.timer.sleep': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.treble': {},
    'level.valve': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.voltage': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.voltage.max': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.voltage.min': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.volume': {
        types: ['number'],
        read: true,
        write: true,
    },
    'level.volume.group': {
        types: ['number'],
        read: true,
        write: true,
    },
    list: {
        types: ['array'],
    },
    location: {},
    'media.add': {},
    'media.album': {},
    'media.artist': {},
    'media.bitrate': {},
    'media.broadcastDate': {
        types: ['string'],
    },
    'media.browser': {},
    'media.clear': {},
    'media.content': {},
    'media.cover': {},
    'media.cover.big': {},
    'media.cover.small': {},
    'media.date': {},
    'media.duration': {
        types: ['number'],
    },
    'media.duration.text': {},
    'media.elapsed': {
        types: ['number'],
    },
    'media.elapsed.text': {},
    'media.episode': {
        types: ['string'],
    },
    'media.genre': {},
    'media.input': {},
    'media.jump': {},
    'media.link': {},
    'media.mode.repeat': {
        types: ['boolean'],
    },
    'media.mode.shuffle': {
        types: ['number'],
    },
    'media.mute': {
        types: ['boolean'],
    },
    'media.mute.group': {
        types: ['boolean'],
    },
    'media.playid': {},
    'media.playlist': {},
    'media.season': {
        types: ['string'],
    },
    'media.seek': {
        types: ['number'],
    },
    'media.state': {},
    'media.title': {},
    'media.title.next': {},
    'media.track': {
        types: ['string'],
    },
    'media.tts': {},
    'media.url': {},
    'media.url.announcement': {},
    sensor: {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.alarm': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.alarm.fire': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.alarm.flood': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.alarm.power': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.alarm.secure': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.contact': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.door': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.light': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.lock': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.motion': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.noise': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.rain': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.switch': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    'sensor.window': {
        types: ['boolean'],
        read: true,
        write: false,
    },
    state: {},
    switch: {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.comfort': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.enable': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.gate': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.light': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.lock': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.lock.door': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.lock.window': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.auto': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.boost': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.color': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.manual': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.moonlight': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.party': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.mode.silent': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.pause': {},
    'switch.power': {
        types: ['boolean'],
        read: true,
        write: true,
    },
    'switch.power.zone': {},
    'switch.setting': {},
    text: {
        types: ['string'],
    },
    'text.phone': {},
    'text.url': {
        types: ['string'],
    },
    'time.interval': {
        types: ['number'],
    },
    'time.span': {
        types: ['number'],
    },
    'time.timeout': {
        types: ['number'],
    },
    url: {},
    'url.audio': {},
    'url.blank': {},
    'url.cam': {},
    'url.icon': {},
    'url.same': {},
    value: {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.battery': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.blind': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.blood.sugar': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.brightness': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.clouds': {},
    'value.co2': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.current': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.curtain': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.default': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.direction': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.direction.max.wind': {},
    'value.direction.min.wind': {},
    'value.direction.wind': {},
    'value.direction.wind.forecast.0': {},
    'value.direction.wind.forecast.1': {},
    'value.distance': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.distance.visibility': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.energy': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.energy.active': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.energy.consumed': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.energy.produced': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.energy.reactive': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.fill': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.frequency': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.gate': {},
    'value.gps': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.gps.accuracy': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.gps.elevation': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.gps.latitude': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.gps.longitude': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.gps.radius': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.health.bmi': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.health.bpm': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.health.calories': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.health.fat': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.health.steps': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.health.weight': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.humidity': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.humidity.max': {},
    'value.humidity.min': {},
    'value.interval': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.lock': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.max': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.min': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.mode.airconditioner': {},
    'value.position': {},
    'value.power': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.power.active': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.power.consumed': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.power.consumption': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.power.produced': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.power.production': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.power.reactive': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.precipitation': {},
    'value.precipitation.chance': {},
    'value.precipitation.day.forecast.0': {},
    'value.precipitation.forecast.0': {},
    'value.precipitation.forecast.1': {},
    'value.precipitation.hour': {},
    'value.precipitation.night.forecast.0': {},
    'value.precipitation.today': {},
    'value.precipitation.type': {},
    'value.pressure': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.pressure.forecast.0': {},
    'value.pressure.forecast.1': {},
    'value.radiation': {},
    'value.rain': {},
    'value.rain.hour': {},
    'value.rain.today': {},
    'value.severity': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.snow': {},
    'value.snow.hour': {},
    'value.snow.today': {},
    'value.snowline': {},
    'value.speed': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.speed.max.wind': {},
    'value.speed.min.wind': {},
    'value.speed.wind': {},
    'value.speed.wind.forecast.0': {},
    'value.speed.wind.forecast.1': {},
    'value.speed.wind.gust': {},
    'value.state': {},
    'value.sun.azimuth': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.sun.elevation': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.temperature': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.temperature.dewpoint': {},
    'value.temperature.feelslike': {},
    'value.temperature.max': {},
    'value.temperature.max.forecast.0': {},
    'value.temperature.max.forecast.1': {},
    'value.temperature.min': {},
    'value.temperature.min.forecast.0': {},
    'value.temperature.min.forecast.1': {},
    'value.temperature.windchill': {},
    'value.tilt': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.time': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.timer': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.uv': {},
    'value.valve': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.voltage': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.warning': {
        types: ['number'],
        read: true,
        write: false,
    },
    'value.waste': {},
    'value.water': {},
    'value.window': {
        types: ['number'],
        read: true,
        write: false,
    },
    'weather.chart.url': {},
    'weather.chart.url.forecast': {},
    'weather.direction.wind': {},
    'weather.direction.wind.forecast.0': {},
    'weather.html': {},
    'weather.icon': {},
    'weather.icon.forecast.1': {},
    'weather.icon.name': {},
    'weather.icon.wind': {},
    'weather.json': {},
    'weather.state': {},
    'weather.state.forecast.0': {},
    'weather.state.forecast.1': {},
    'weather.title': {},
    'weather.title.forecast.0': {},
    'weather.title.short': {},
    'weather.type': {},
};

module.exports = {
    STATE_ROLE_RULES,
};
